name: Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Fix Kotlin Native warnings
        run: echo "kotlin.native.ignoreDisabledTargets=true" >> gradle.properties

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.run_number }}
          path: composeApp/build/outputs/apk/**/*.apk
